# Generated by Django 3.0.3 on 2020-04-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_allergen_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='restaurant_pics'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='allergen',
            field=models.ManyToManyField(blank=True, to='navigation.Allergen'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='classification',
            field=models.CharField(choices=[('VE', 'Vegan'), ('GF', 'Gluten Free'), ('DF', 'Not Specified')], default='DF', max_length=3),
        ),
    ]
